### ISSUE TITLE
Digital upskilling pics

### ISSUE THREAD

**Issue by Nicole-Murphy-DTA** [govau/digital-summit-2020#112]
Hi Jesse

Here are the speaker pics.
![LyndonBlanchard](https://user-images.githubusercontent.com/72477343/97951828-8b83ec00-1def-11eb-9131-03582c998780.png)
![Jennifer_Mulveny](https://user-images.githubusercontent.com/72477343/97951830-8d4daf80-1def-11eb-96a4-d1484796088d.jpg)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/113
