### ISSUE TITLE
New exhibitors

### ISSUE THREAD

**Issue by Nicole-Murphy-DTA** [govau/digital-summit-2020#24]
Morning Jesse

Can you please upload the following logos (all exhibitors)

- Clevertar (Paul should have)
- Babl (Paul should have)
- Digital Profession (attached)
- DTA (use the standard dta logo, which I assume you have access to).

![digital profession stream](https://user-images.githubusercontent.com/72477343/95521095-77c5af80-0a14-11eb-9c28-cf622f81c5c0.png)
![babl](https://user-images.githubusercontent.com/4567284/95524418-10f8c400-0a1d-11eb-979a-c4913b0354f4.png)
![clevertar](https://user-images.githubusercontent.com/4567284/95524419-11915a80-0a1d-11eb-8adb-60a3deaeb4ff.png)
![DTA](https://user-images.githubusercontent.com/4567284/95524420-1229f100-0a1d-11eb-9113-88d491e57d15.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/29
