### ISSUE TITLE
New exhibitor - PSIN

### ISSUE THREAD

**Issue by Nicole-Murphy-DTA** [govau/digital-summit-2020#25]
Sorry Jesse - forgot I hadn't given you this one either. Another exhibitor.
![psin](https://user-images.githubusercontent.com/4567284/95524379-f0306e80-0a1c-11eb-934c-16454ca4eaba.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/29
