### ISSUE TITLE
Add logo to website

### ISSUE THREAD

**Issue by Nicole-Murphy-DTA** [govau/digital-summit-2020#35]
Hi Jesse

Can you please add the PwC logo to the website as a Gold sponsor?

Thanks

Nicole
![pwc](https://user-images.githubusercontent.com/4567284/95937299-29a11980-0e23-11eb-92e4-826add97f1c5.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/37
