### ISSUE TITLE
New exhibitor to add

### ISSUE THREAD

**Issue by Nicole-Murphy-DTA** [govau/digital-summit-2020#41]
Hi Jesse

Please add Internetrix as an exhibitor to the website.

Thanks

Nicole

**Comment by imperator99** [comment]
@Nicole-Murphy-DTA can you please update this issue with the image when it arrives?

**Comment by imperator99** [comment]
![internetrix](https://user-images.githubusercontent.com/4567284/96385420-8dd72b00-11df-11eb-9b3d-f04da8efd52e.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/51
