### ISSUE TITLE
New sponsor/exhibitor

### ISSUE THREAD

**Issue by Nicole-Murphy-DTA** [govau/digital-summit-2020#65]
Morning Jesse

Can you please add the following:

ASG Group - exhibitor
Delv - exhibitor

Thanks

**Comment by imperator99** [comment]
![asg](https://user-images.githubusercontent.com/4567284/96531636-d6711000-12d5-11eb-93ec-5ddbc7757381.png)

**Comment by imperator99** [comment]
![delv](https://user-images.githubusercontent.com/4567284/96532535-d3771f00-12d7-11eb-8dcc-68bdae2a5013.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/67
