### ISSUE TITLE
Update Accenture Sponsor Profile

### ISSUE THREAD

**Issue by LounyTunes** [govau/digital-summit-2020#71]
Hi team

Could you please update the Accenture profile on the Summit website (https://events.digital.gov.au/digital-summit-2020/sponsors/#accenture) to the below?

Accenture is a global professional services company with leading capabilities in digital, cloud and security. Combining unmatched experience and specialized skills across more than 40 industries, we offer Strategy and Consulting, Interactive, Technology and Operations services—all powered by the world’s largest network of Advanced Technology and Intelligent Operations centers. Our 506,000 people deliver on the promise of technology and human ingenuity every day, serving clients in more than 120 countries. We embrace the power of change to create value and shared success for our clients, people, shareholders, partners and communities.

Thank you for your help!
Kind regards
Jhess

**Comment by imperator99** [comment]
Hi @LounyTunes thanks for your issue.

Gold sponsors are limited to a 50-word profile on the website. I've edited down the original profile from the one originally sent to meet this limitation. I'm happy to update if you can supply a 50-word profile.

Thanks,
Jesse.

**Comment by LounyTunes** [comment]
@imperator99 Accenture has come back at us with the requested change:

"Accenture is a global professional services company with leading capabilities in digital, cloud and security. Combining unmatched experience and specialised skills across more than 40 industries, Accenture offers Strategy and Consulting, Interactive, Technology and Operations services—all powered by the world’s largest network of Advanced Technology and Intelligent Operations centers."

Thanks,
Lou

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/digital-summit-2020/pull/76
